import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`
          /* Custom Scrollbar - 핑크색만 둥둥 뜨게 */
          ::-webkit-scrollbar {
            width: 30px;
            height: 30px;
            background: transparent;
          }
          ::-webkit-scrollbar-track {
            background: transparent;
          }
          ::-webkit-scrollbar-thumb {
            background: linear-gradient(180deg, #ff6b9d 0%, #c44569 50%, #ff6b9d 100%);
            border-radius: 20px;
            border: none;
          }
          ::-webkit-scrollbar-thumb:hover {
            background: linear-gradient(180deg, #ff85ad 0%, #d45579 50%, #ff85ad 100%);
          }
          ::-webkit-scrollbar-button {
            display: none;
            width: 0;
            height: 0;
          }
          ::-webkit-scrollbar-corner {
            background: transparent;
          }
          html {
            scrollbar-width: thin;
            scrollbar-color: #ff6b9d transparent;
          }
          /* 4분할 박스 안 스크롤바 숨기기 */
          .hide-scrollbar::-webkit-scrollbar {
            display: none;
          }
          .hide-scrollbar {
            -ms-overflow-style: none;
            scrollbar-width: none;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
